sindromes_diagnosticos = [
	{
		"SINDROME": "ARRITMIAS CARDÍACAS",
		"DIAGNOSTICOS": [
			"MARCAPASSO",
			"BRE",
			"BAV PRIMEIRO GRAU",
			"ARRITMIA",
			"TAQUICARDIA",
			"EXTRASSÍSTOLE VENTRICULAR",
			"PRÉ-EXCITAÇÃO VENTRICULAR",
			"FA",
			"SÍNDROME DE WOLF PARKISON WHITE"
		]
	},
	{
		"SINDROME": "AVALIAÇÃO CARDIOLÓGICA",
		"DIAGNOSTICOS": [
			"AVALIAÇÃO CARDIOLÓGICA",
			"LIBERAÇÃO CIRÚRGICA"
		]
	},
	{
		"SINDROME": "CARDIOMIOPATIAS",
		"DIAGNOSTICOS": [
			"HIPERTROFIA VENTRICULAR ESQUERDA",
			"CARDIOMIOPATIA"
		]
	},
	{
		"SINDROME": "DOENÇA ARTERIAL CORONARIANA",
		"DIAGNOSTICOS": [
			"ANGINA",
			"CORONARIOPATIA",
			"IAM"
		]
	},
	{
		"SINDROME": "DOENÇA CONGÊNITA DO CORAÇÃO",
		"DIAGNOSTICOS": [
			"CIA",
			"DOENÇA CARDÍACA CONGÊNITA",
			"CIRURGIA DE FECHAMENTO DE CANAL ARTERIAL",
			"CARDIOPATIA INFÂNCIA",
			"CIA TRATADA"
		]
	},
	{
		"SINDROME": "DOENÇAS VALVARES",
		"DIAGNOSTICOS": [
			"PROLAPSO MITRAL",
			"VALVOPATIA",
			"SOPRO",
		]
	},
	{
		"SINDROME": "HAS",
		"DIAGNOSTICOS": [
			"HAS"
		]
	},
	{
		"SINDROME": "INSUFICIÊNCIA CARDÍACA",
		"DIAGNOSTICOS": [
			"INSUFICIÊNCIA CARDÍACA",
			"DOENÇA DE CHAGAS"
		]
	},
	{
		"SINDROME": "OUTRAS DOENÇAS",
		"DIAGNOSTICOS": [
			"TAG",
			"LES",
			"HIPOTIREOIDISMO",
			"ESTEATOSE HEPÁTICA",
			"DIABETES MELLITUS",
			"OSTEOPOROSE",
			"EPILEPSIA",
			"DPOC",
			"CIRROSE",
			"OBESIDADE",
			"OUTRAS DOENÇAS",
			"ANSIEDADE",
			"GESTAÇÃO",
			"DOENÇA RENAL CRÔNICA",
			"MIGRÂNEA",
			"DISLIPIDEMIA",
			"OSTEOARTROSE",
			"SD. MORRIS",
			"FIBROMIALGIA",
			"DEPRESSÃO",
			"ANEMIA",
			"ALZHEIMER",
			"ASMA",
			"AVC",
			"MENOPAUSA",
			"INSUFICIÊNCIA VENOSA"
		]
	},
	{
		"SINDROME": "REALIZAR EXAMES",
		"DIAGNOSTICOS": [
			"REALIZAR EXAMES"
		]
	},
	{
		"SINDROME": "VALVOPATIA",
		"DIAGNOSTICOS": [
			"TROCA DE VALVA AÓRTICA",
			"ESTENOSE AÓRTICA",
			"PVM COM IM DISCRETA"
		]
	}
]